# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  MyVar: -1
  
stages:
- stage: Save_Variable
 
  jobs:
  - job: Save_Variable
    steps:
    - task: PowerShell@2
      name: MyOutputVar
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[task.setvariable variable=MyVar;isOutput=true]2"
          
          Write-Host $(MyVar)
      # - powershell: Write-Host "##vso[task.setvariable variable=MyVar;isOutput=true]2"
      # - pwsh: Write-Host "##vso[task.setvariable variable=MyVar;isOutput=true]NewVal"
        # name: MyOutputVar
 
- stage: Read_Variables
  dependsOn: Save_Variable
  variables:
    prevStageVar: $[stageDependencies.Save_Variable.Save_Variable.outputs['MyOutputVar.MyVar']]

  jobs:
  - job: Read_Variable
    steps:

    - task: PowerShell@2
      condition: eq(variables.prevStageVar, 2)
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Get Stage variable: $(prevStageVar)"'

    # - ${{ if eq(variables.prevStageVar, 2) }}:
    #   - powershell: 'Write-Host "Get Stage variable: $(prevStageVar)"'

    # # ${{ if eq(variables.prevStageVar, 2) }}:
    # - powershell: 'Write-Host "#2 Get Stage variable: $(prevStageVar)"'
