- job: Helm
  displayName: 'Build and Push Helm Chart'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - checkout: self
      fetchDepth: 1

    - task: HelmInstaller@1
      displayName: 'Initialize Helm'
      inputs:
        helmVersionToInstall: '$(helmVersion)'

    - task: HelmDeploy@0
      displayName: 'Package Helm Chart'
      inputs:
        command: 'package'
        chartPath: 'parrot/src/parrot/charts/parrot'
        chartVersion: '$(Build.BuildNumber)'
        save: false

    - task: AzureCLI@2
      displayName: 'Push Helm Chart'
      inputs:
        azureSubscription: '946de978-cdf5-4d29-bf9b-014a95e89e63'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr helm push \
            --name $(containerRegistry) \
            $(Build.ArtifactStagingDirectory)/$(containerRepository)-$(Build.BuildNumber).tgz